import { newSalt, deriveKey, encrypt, decrypt } from "./crypto.js";
import { REGION, API, CLIENT_ID } from "./config.js"; // generated by deploy.sh

const $ = (id) => document.getElementById(id);
const view = (v) => {
  ["auth", "confirm", "unlock"].forEach((x) => ($(x).hidden = x !== v));
  $("gate").hidden = v === "vault"; $("vault").hidden = v !== "vault";
};
let toast;
const say = (t = "", ok = false) => {
  clearTimeout(toast); $("msg").textContent = t; $("msg").className = (t ? "show " : "") + (ok ? "ok" : "");
  if (t) toast = setTimeout(() => ($("msg").className = ""), 4000);
};

let token = null, key = null, meta = null, entries = [];

// ---- Cognito (plain HTTPS JSON API, no SDK) ----
async function idp(target, body) {
  const r = await fetch(`https://cognito-idp.${REGION}.amazonaws.com/`, {
    method: "POST",
    headers: { "content-type": "application/x-amz-json-1.1", "x-amz-target": "AWSCognitoIdentityProviderService." + target },
    body: JSON.stringify({ ClientId: CLIENT_ID, ...body }),
  });
  const j = await r.json();
  if (!r.ok) throw Object.assign(new Error(j.message || j.__type), { type: j.__type });
  return j;
}

// ---- Vault API (JWT-protected) ----
async function api(method, path, body) {
  const r = await fetch(API + path, { method, headers: { authorization: token }, body });
  if (r.status === 401) { signOut("Session expired, sign in again."); throw new Error("expired"); }
  if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || r.status);
  return r.status === 204 ? null : r.json();
}

function signOut(text = "") {
  token = key = meta = null; entries = [];
  document.querySelectorAll("input").forEach((i) => (i.value = ""));
  $("list").replaceChildren(); $("addDlg").close(); view("auth"); say(text);
}

// ---- Auth forms ----
$("auth").onsubmit = async (e) => {
  e.preventDefault(); say();
  try {
    const r = await idp("InitiateAuth", { AuthFlow: "USER_PASSWORD_AUTH", AuthParameters: { USERNAME: $("email").value, PASSWORD: $("pw").value } });
    token = r.AuthenticationResult.IdToken; $("pw").value = "";
    const items = await api("GET", "/vault");
    meta = items.find((i) => i.id === "META");
    meta &&= JSON.parse(meta.blob);
    entries = items.filter((i) => i.id !== "META");
    $("mp2").hidden = !!meta; $("mp2").required = !meta;
    $("unlockTitle").textContent = meta ? "Unlock vault" : "Create master passphrase";
    $("unlockHelp").textContent = meta ? "Your vault is encrypted with your master passphrase." :
      "This encrypts everything in your browser. AWS never sees it. If you forget it, your data cannot be recovered.";
    view("unlock");
  } catch (x) {
    if (x.type === "UserNotConfirmedException") { view("confirm"); say("Verify your email first.", true); }
    else if (x.message !== "expired") say(x.message);
  }
};

$("signup").onclick = async () => {
  say();
  try {
    await idp("SignUp", { Username: $("email").value, Password: $("pw").value, UserAttributes: [{ Name: "email", Value: $("email").value }] });
    view("confirm"); say("Code sent to your email.", true);
  } catch (x) { say(x.message); }
};

$("confirm").onsubmit = async (e) => {
  e.preventDefault(); say();
  try {
    await idp("ConfirmSignUp", { Username: $("email").value, ConfirmationCode: $("code").value.trim() });
    view("auth"); say("Verified. Now sign in.", true);
  } catch (x) { say(x.message); }
};

// ---- Master passphrase: first time creates salt + check value, afterwards verifies it ----
$("unlock").onsubmit = async (e) => {
  e.preventDefault(); say();
  try {
    const mp = $("mp").value;
    if (meta) {
      const k = await deriveKey(mp, meta.salt);
      try { await decrypt(k, meta.check); } catch { throw new Error("Wrong master passphrase"); }
      key = k;
    } else {
      if (mp.length < 12) throw new Error("Use at least 12 characters");
      if (mp !== $("mp2").value) throw new Error("Passphrases do not match");
      const salt = newSalt(), k = await deriveKey(mp, salt);
      await api("PUT", "/vault/META", JSON.stringify({ salt, check: await encrypt(k, { ok: 1 }) }));
      key = k;
    }
    $("mp").value = $("mp2").value = "";
    entries = await Promise.all(entries.map(async (i) => ({ id: i.id, ...(await decrypt(key, JSON.parse(i.blob))) })));
    $("who").textContent = $("email").value;
    view("vault"); render();
  } catch (x) { if (x.message !== "expired") say(x.message); }
};

// ---- Dashboard ----
// textContent only (never innerHTML): stored data can never inject HTML or script
const el = (tag, cls, text = "") => Object.assign(document.createElement(tag), { className: cls, textContent: text });
const hue = (s) => [...s].reduce((h, c) => (h * 31 + c.charCodeAt(0)) % 360, 7);

function card(v) {
  const box = el("div", "entry"), head = el("div", "head"), meta = el("div", "meta"), acts = el("div", "acts");
  const av = el("div", "avatar", (v.site.trim()[0] || "?").toUpperCase());
  av.style.background = `hsl(${hue(v.site.toLowerCase())} 65% 50%)`;
  const pw = el("code", "", "••••••••••");
  const btn = (label, cls, fn) => Object.assign(el("button", cls, label), { onclick: fn });
  const show = btn("👁 Show", "", () => { const on = pw.textContent.startsWith("•"); pw.textContent = on ? v.pass : "••••••••••"; show.textContent = on ? "🙈 Hide" : "👁 Show"; });
  const copy = btn("📋 Copy", "", async () => { await navigator.clipboard.writeText(v.pass); say("Password copied", true); });
  const del = btn("🗑 Delete", "del", async () => {
    if (!confirm(`Delete ${v.site}?`)) return;
    try { await api("DELETE", "/vault/" + v.id); entries = entries.filter((x) => x.id !== v.id); render(); } catch (x) { say(x.message); }
  });
  meta.append(el("b", "", v.site), el("span", "", v.user)); head.append(av, meta); acts.append(show, copy, del);
  box.append(head, pw, acts);
  return box;
}

function render() {
  const q = $("search").value.toLowerCase();
  const shown = entries.filter((v) => (v.site + v.user).toLowerCase().includes(q)).sort((a, b) => a.site.localeCompare(b.site));
  $("count").textContent = entries.length;
  $("list").replaceChildren(...shown.map(card));
  $("empty").hidden = shown.length > 0;
  $("empty").replaceChildren(entries.length
    ? el("b", "", "No matches")
    : el("b", "", "Your vault is empty"), el("span", "", entries.length ? "Try a different search." : "Click “Add password” to save your first one."));
}
$("search").oninput = render;

// ---- Add dialog ----
$("openAdd").onclick = () => $("addDlg").showModal();
$("cancel").onclick = () => $("addDlg").close();

const strength = (p) => Math.min(4, (p.length >= 8) + (p.length >= 12) + (/[a-z]/.test(p) && /[A-Z]/.test(p)) + (/\d/.test(p) && /[^\w\s]/.test(p)));
$("pass").oninput = () => ($("meter").className = "s" + strength($("pass").value));

$("add").onsubmit = async (e) => {
  e.preventDefault();
  const v = { site: $("site").value, user: $("user").value, pass: $("pass").value }, id = "E-" + crypto.randomUUID();
  try {
    await api("PUT", "/vault/" + id, JSON.stringify(await encrypt(key, v))); // plaintext never leaves the browser
    entries.push({ id, ...v }); e.target.reset(); $("pass").type = "password"; $("meter").className = "";
    $("addDlg").close(); render(); say("Saved & encrypted 🔒", true);
  } catch (x) { say(x.message); }
};

$("gen").onclick = () => {
  const cs = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%^&*", lim = 256 - (256 % cs.length), out = [];
  while (out.length < 20) for (const n of crypto.getRandomValues(new Uint8Array(32))) if (n < lim && out.length < 20) out.push(cs[n % cs.length]); // rejection sampling: no modulo bias
  $("pass").type = "text"; $("pass").value = out.join(""); $("pass").oninput();
};


$("out1").onclick = $("out2").onclick = () => signOut();
